@baseUrl=https://localhost/api/v1

###
POST {{baseUrl}}/generic/clear

###
POST {{baseUrl}}/generic/load-samples

###
GET {{baseUrl}}/app/config

###
PUT {{baseUrl}}/app/config
Content-Type: application/json

{"dummyApi": false}


### Settings
GET {{baseUrl}}/user/1/settings

### Settings
PUT {{baseUrl}}/user/1/settings
Content-Type: application/json

[
  {"key": "k1", "value": "v1"},
  {"key": "k2", "value": "v2"}
]



### Researcher API
@researcherBaseUrl=http://localhost:8080

###
GET {{researcherBaseUrl}}/

### Swagger UI
GET {{researcherBaseUrl}}/docs

### OpenAPI
GET {{researcherBaseUrl}}/openapi.json

### 
GET {{researcherBaseUrl}}/research

###
POST {{researcherBaseUrl}}/research
Content-Type: application/json

{}
