FROM python:3.12.3

WORKDIR /code

COPY ./requirements.txt ./requirements.txt
RUN echo "\ndebugpy\n" >> ./requirements.txt

RUN --mount=type=cache,mode=0755,target=/root/.cache \
  pip install -r requirements.txt

# CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]


CMD ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "80"]
